# docker-compose.yml

version: "3"

services:
#  web:
#    image: web
#    container_name: web
#    restart: always
#    networks:
#      - my-network
#    volumes:
#      - ./:/appNext
#      - /appNext/node_modules
#      - /appNext/.next
#    ports:
#      - 3000:3000

  pgtest:
    image: pgtest
    container_name: pgtest
    networks:
      - my-network
    ports:
      - 5432:5432/tcp

  node:
    image: node
    container_name: node
    networks:
      - my-network
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - pgtest

  wsocket:
    image: ws
    container_name: wsocket
    networks:
      - my-network
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    depends_on:
      - pgtest

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-user@domain.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-SuperSecret}

    ports:
      - "80:80"
    networks:
      - my-network
    restart: unless-stopped
    depends_on:
      - pgtest

networks:
  my-network:
    driver: bridge
